// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file

import { resolveBundledFilePath } from "@opentui/core"
import type { FiletypeParserOptions, InjectionMapping } from "@opentui/core"

interface FileImportModule {
  readonly default: string
}

const bundledAssetLoaders: Record<string, () => Promise<FileImportModule>> = {
  "tree-sitter-assets/bash/highlights.scm": () => import("./tree-sitter-assets/bash/highlights.scm" as string, { with: { type: "file" } }),
  "tree-sitter-assets/bash/tree-sitter-bash.wasm": () => import("./tree-sitter-assets/bash/tree-sitter-bash.wasm" as string, { with: { type: "file" } }),
  "tree-sitter-assets/python/highlights.scm": () => import("./tree-sitter-assets/python/highlights.scm" as string, { with: { type: "file" } }),
  "tree-sitter-assets/python/tree-sitter-python.wasm": () => import("./tree-sitter-assets/python/tree-sitter-python.wasm" as string, { with: { type: "file" } }),
}

interface DefaultParserDescriptor {
  readonly filetype: string
  readonly aliases?: readonly string[]
  readonly queries: {
    readonly highlights: readonly string[]
    readonly injections?: readonly string[]
  }
  readonly wasm: string
  readonly injectionMapping?: InjectionMapping
}

const defaultParserDescriptors: readonly DefaultParserDescriptor[] = [
  {
    "filetype": "bash",
    "aliases": [
      "sh",
      "shell"
    ],
    "queries": {
      "highlights": [
        "tree-sitter-assets/bash/highlights.scm"
      ]
    },
    "wasm": "tree-sitter-assets/bash/tree-sitter-bash.wasm"
  },
  {
    "filetype": "python",
    "aliases": [
      "py"
    ],
    "queries": {
      "highlights": [
        "tree-sitter-assets/python/highlights.scm"
      ]
    },
    "wasm": "tree-sitter-assets/python/tree-sitter-python.wasm"
  }
]

export const defaultParserAssetPaths: readonly string[] = [
  ...new Set(
    defaultParserDescriptors.flatMap((parser) => [
      ...parser.queries.highlights,
      parser.wasm,
      ...(parser.queries.injections ?? []),
    ]),
  ),
]

let cachedParsers: Promise<FiletypeParserOptions[]> | undefined

export function getParsers(): Promise<FiletypeParserOptions[]> {
  cachedParsers ??= Promise.all(defaultParserDescriptors.map(resolveDefaultParser))
  return cachedParsers
}

async function resolveDefaultParser(parser: DefaultParserDescriptor): Promise<FiletypeParserOptions> {
  const queries: FiletypeParserOptions["queries"] = {
    highlights: await Promise.all(parser.queries.highlights.map(resolveParserAsset)),
  }
  if (parser.queries.injections) {
    queries.injections = await Promise.all(parser.queries.injections.map(resolveParserAsset))
  }

  return {
    filetype: parser.filetype,
    ...(parser.aliases ? { aliases: [...parser.aliases] } : {}),
    queries,
    wasm: await resolveParserAsset(parser.wasm),
    ...(parser.injectionMapping ? { injectionMapping: parser.injectionMapping } : {}),
  }
}

function resolveParserAsset(relativePath: string): Promise<string> {
  const loadBundledFile = bundledAssetLoaders[relativePath]
  if (!loadBundledFile) {
    throw new Error(`Unknown parser asset: ${JSON.stringify(relativePath)}`)
  }
  return resolveBundledFilePath(
    relativePath,
    loadBundledFile,
    new URL(`./${relativePath}`, import.meta.url),
    import.meta.url,
    { loadBundledFileFallback: true, useAssetRoot: false },
  )
}
